Declare missing dependency on python3-importlib-resources
ros2/sros2 pull request #249
Opened 2021-01-20 21:17 UTC by cottsay

Requires ros/rosdistro#28001.

Used here:
https://github.com/ros2/sros2/blob/74da58f7433833562226f1cf05113229cee11005/sros2/sros2/policy/__init__.py#L19-L25

The source code supports using the `importlib_resources` package, but on all of the platforms we're running regular builds for, we have Python 3.7, which provides the package as part of Python itself.

2021-01-26 07:37 UTC, mikaelarguedas commented
thanks for the fix.

This seems to introduce pip dependencies on some platforms listed in REP-2000 (Debian Buster).
Does this mean that sros2 will not be package-able on those platforms after this fix ?

2021-01-26 09:15 UTC, cottsay commented
> Does this mean that sros2 will not be package-able on those platforms after this fix?

It appears that is the case. It actually won't matter, though, because `ament_package` itself requires `importlib_resources`, so nothing is going to work until the package is available.

I wasn't aware of this - I'll bring it up at the next ROS 2 meeting and we'll discuss the impact this will have on Galactic. You can hold this PR if you like, but there are a few other packages in `ros2.repos` that are already taking this dependency.

2021-01-26 13:56 UTC, mikaelarguedas commented
> It appears that is the case. It actually won't matter, though, because ament_package itself requires importlib_resources, so nothing is going to work until the package is available.

Fair enough, :+1: for this then and we'll see if a follow-up is needed based on the result of the ROS 2 meeting discussion

2021-01-26 13:58 UTC, mikaelarguedas requested changes

2021-01-26 13:58 UTC, mikaelarguedas commented on sros2/package.xml
> +  <test_depend>python3-importlib-resources</test_depend>
```suggestion
```
From the [docs](http://wiki.ros.org/catkin/package.xml#Build.2C_Run.2C_and_Test_Dependencies) "Test Dependencies specify only additional dependencies for unit tests. They should never duplicate any dependencies already mentioned as build or run dependencies."

2021-01-28 18:17 UTC, mikaelarguedas commented on sros2/package.xml
> +  <test_depend>python3-importlib-resources</test_depend>
I went ahead and merged this suggestion. I'll let another @ros2/security-reviewers give the second approval

2021-01-28 18:21 UTC, cottsay commented
> I'll bring it up at the next ROS 2 meeting and we'll discuss the impact this will have on Galactic

In the ROS 2 meeting we decided to target Bullseye for a variety of reasons, `importlib_resources` among them. It's also worth noting that we haven't built any binary packages for Debian in ROS 2 to-date.

2021-01-28 18:24 UTC, mikaelarguedas approved these changes

2021-01-28 18:26 UTC, mikaelarguedas commented
> importlib_resources among them. It's also worth noting that we haven't built any binary packages for Debian in ROS 2 to-date.

:+1:, it's still good to know we're not standing in the way of people that may want to build debs for their own applications

2021-01-28 21:37 UTC, kyrofa commented
> The source code supports using the importlib_resources package, but on all of the platforms we're running regular builds for, we have Python 3.7, which provides the package as part of Python itself.

Post-Foxy, which supported platforms use a Python prior to 3.7?

2021-01-28 21:42 UTC, cottsay commented
My initial comment was incorrect - [it was introduced in Python 3.9](https://pypi.org/project/importlib-resources/), so anything earlier than that will need the package. Which is pretty much all supported platforms.

2021-01-28 21:44 UTC, kyrofa commented
Ahhh, now I'm less confused :) .

2021-01-28 21:44 UTC, kyrofa approved these changes

2021-01-28 21:46 UTC, merged