build only selected packages to enable security.
ros2/sros2 pull request #325
Opened 2024-12-04 18:40 UTC by fujitatomoya

build only selected packages to enable security to save time.

2024-12-04 18:40 UTC, fujitatomoya commented
related to https://github.com/ros2/ros2_documentation/pull/4890

2024-12-04 18:41 UTC, fujitatomoya commented
@clalancette can you take a look?

2024-12-06 14:34 UTC, clalancette requested changes
Can you change the rest of the "ROS2" -> "ROS 2" in the docs as well?

Also, just double-checking; have you checked that this compile-line is enough to enable security?

2024-12-06 14:34 UTC, clalancette commented on SROS2_Windows.md
>  To build the ROS2 code with security extensions, call:
```suggestion
To build the ROS 2 code with security extensions, call:
```

(I know it is not directly connected with this PR, but while we are here we may as well fix it)

2025-01-22 00:14 UTC, fujitatomoya commented
@clalancette 

> Also, just double-checking; have you checked that this compile-line is enough to enable security?

Yes i have confirmed that is no problem to enable security.

2025-01-28 19:50 UTC, fujitatomoya commented
@clalancette friendly ping, https://github.com/ros2/ros2_documentation/pull/4890 has been merged already.

2025-01-28 20:20 UTC, clalancette approved these changes

2025-01-28 22:01 UTC, merged

2025-01-28 22:01 UTC, fujitatomoya commented
@Mergifyio backport jazzy humble